apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-azure
  namespace: spring
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: spring-azure
          imagePullPolicy: Always
