name: azure github actions

on:
  push:
    branches:
      - master

jobs:
  building-and-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Maven Validate
        run: mvn validate

      - name: Maven Compile
        run: mvn compile

      - name: Maven Package
        run: mvn package

      - name: Maven clean install
        run: mvn clean install
