name: azure github actions

env:
  MAVEN_VERSION: 3.9.9
  JAVA_VERSION: 21
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

on:
  push:
    branches:
      - master


jobs:
  building-and-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}   # Todo Make It '21'
          distribution: 'temurin' # 'adopt'
          architecture: x64
          cache: 'maven' # Strongly recommended for faster builds!
          cache-dependency-path: 'pom.xml' # Or '**/pom.xml' for multi-module projects

      - name: Setup Maven
        uses: stCarolas/setup-maven@v4.4
        with:
          maven-version: ${{ env.MAVEN_VERSION }} #3.8.2

      - name: Maven Validate
        run: mvn validate

      - name: Maven Package
        run: mvn package

      - name: Maven clean install
        run: mvn clean install

      - name: Log in to Docker Hub
        uses: docker/login-action@v3 # Using the official Docker login action
        with:
         username: ${{ secrets.DOCKER_USERNAME }} # Accessing the username from GitHub Secrets
         password: ${{ secrets.DOCKER_PASSWORD }} # Accessing the password/token from GitHub Secrets

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build docker image
        run: docker build -t spring-azure .
      - name: Tag docker image
        run: docker tag spring-azure harshdeep09012004/spring-azure:v1.00
      - name: Push docker image
        run: docker push harshdeep09012004/spring-azure:v1.00
      - name: Getting Docker Images
        run: |
          docker images
          docker ps -a

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set AKS context
        uses: azure/aks-set-context@v4
        with:
          resource-group: Project01
          cluster-name: Cluster0001

      - name: Kubectl apply (AKS overlay)
        run: |
          kubectl apply -f k8s/base/deployment.yaml -n spring
          kubectl apply -f k8s/base/service.yaml -n spring
          kubectl get all -n spring
          kubectl get pods,svc -n spring

